fn pi -> float : int iterations {
    float pi = 0.0
    float sign = 1.0
    for int i = 0 : i < iterations : i = i + 1 {
        pi = pi + sign / (2.0 * i + 1.0)
        sign = -sign

        if i % 10000 == 0 {
            print : ("PI:",4*pi)
        }
    }
    pi * 4.0
    return pi * 4.0
}


fn main -> int {
    int iterations = 10000000
    float pi = pi : (iterations)
    print : (pi)
    return 0
}

main : ()